spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        hide-instance-url: true
      hazelcast:
        start-embedded: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: host.docker.internal

server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: ALWAYS
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
      post:
        enabled: true

logging:
  level:
    com.hazelcast: DEBUG