spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        hide-instance-url: false  # Show URLs in local development
      hazelcast:
        start-embedded: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://registry:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    configprops:
      show-values: ALWAYS
    env:
      show-values: ALWAYS
      post:
        enabled: true
