spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        hide-instance-url: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: host.docker.internal

server:
  port: 9080